apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql-repo:db
    imagePullPolicy: IfNotPresent
    name: mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
  