apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: mysql
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: mysql
        image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql-repo:db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw