apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: backend
  name: mysql
  namespace: mysql-ns
spec:
  containers:
  - image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql-repo:db
    imagePullPolicy: IfNotPresent
    name: mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
  