apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: webapp
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: mysql
        image: ImageURI