apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-webapp
  namespace: webapp-ns
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-app-repo:app
        ports:
        - containerPort: 8080
          Protocol: TCP
        env: 
        - name: DBHOST
          value: "10.244.0.14"
        - name: DBPORT
          value: "3306"
        - name: DBUSER 
          value: root
        - name: DBPWD
          value: pw
