apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: webapp
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    name: webapp
    tier: frontend