apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-app-repo:app
    imagePullPolicy: IfNotPresent
    name: webapp
    resources: {}
    ports:
    - containerPort: 8081
    env:
    - name: DBHOST
      value: 10.244.0.8
      
