apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp-ns
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
     app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - image: 940156990945.dkr.ecr.us-east-1.amazonaws.com/clo835-app-repo:app
        name: webapp
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "10.244.0.8"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw